/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.Checkbox;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author harshana shaminda
 */
public class registerform extends javax.swing.JFrame {

    /**
     * Creates new form registerform
     */
    public registerform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txtpwd = new javax.swing.JPasswordField();
        txtuname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtcpwd = new javax.swing.JPasswordField();
        txtemail = new javax.swing.JTextField();
        chkb = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        lb_un = new javax.swing.JLabel();
        lb_fn = new javax.swing.JLabel();
        lb_ln = new javax.swing.JLabel();
        lb_pwd = new javax.swing.JLabel();
        lb_cpwd = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        chk_agree = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lb_back = new javax.swing.JLabel();

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\if_Audio_-_Video_-_Game_01_2298385.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Register");
        jLabel3.setRequestFocusEnabled(false);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 200, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 70, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 10));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirm Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 50, 10));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 180, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 180, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 180, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 180, 10));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 180, 10));

        txtpwd.setBackground(new java.awt.Color(36, 47, 65));
        txtpwd.setForeground(new java.awt.Color(204, 204, 204));
        txtpwd.setBorder(null);
        txtpwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpwdFocusGained(evt);
            }
        });
        txtpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpwdMouseClicked(evt);
            }
        });
        jPanel2.add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 180, -1));
        txtpwd.getAccessibleContext().setAccessibleName("txtpwd");

        txtuname.setBackground(new java.awt.Color(36, 47, 65));
        txtuname.setForeground(new java.awt.Color(204, 204, 204));
        txtuname.setBorder(null);
        txtuname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtunameMouseClicked(evt);
            }
        });
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        jPanel2.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 180, 30));
        txtuname.getAccessibleContext().setAccessibleName("txtuname");

        txtfname.setBackground(new java.awt.Color(36, 47, 65));
        txtfname.setForeground(new java.awt.Color(204, 204, 204));
        txtfname.setBorder(null);
        txtfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfnameMouseClicked(evt);
            }
        });
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 180, -1));
        txtfname.getAccessibleContext().setAccessibleName("txtfname");

        txtlname.setBackground(new java.awt.Color(36, 47, 65));
        txtlname.setForeground(new java.awt.Color(204, 204, 204));
        txtlname.setBorder(null);
        txtlname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlnameMouseClicked(evt);
            }
        });
        jPanel2.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 180, -1));
        txtlname.getAccessibleContext().setAccessibleName("txtlname");

        txtcpwd.setBackground(new java.awt.Color(36, 47, 65));
        txtcpwd.setForeground(new java.awt.Color(204, 204, 204));
        txtcpwd.setBorder(null);
        txtcpwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcpwdFocusGained(evt);
            }
        });
        jPanel2.add(txtcpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 180, -1));
        txtcpwd.getAccessibleContext().setAccessibleName("txtcpwd");

        txtemail.setBackground(new java.awt.Color(36, 47, 65));
        txtemail.setForeground(new java.awt.Color(204, 204, 204));
        txtemail.setBorder(null);
        txtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemailMouseClicked(evt);
            }
        });
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 180, -1));
        txtemail.getAccessibleContext().setAccessibleName("txtemail");

        chkb.setBackground(new java.awt.Color(36, 47, 65));
        chkb.setForeground(new java.awt.Color(204, 204, 204));
        chkb.setText("I accept terms & conditions");
        chkb.setBorder(null);
        chkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbActionPerformed(evt);
            }
        });
        jPanel2.add(chkb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 20));
        chkb.getAccessibleContext().setAccessibleName("chk1");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Register");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 100, 30));
        jButton1.getAccessibleContext().setAccessibleName("rbnregister");

        lb_un.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_un.setForeground(java.awt.Color.red);
        jPanel2.add(lb_un, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 80, 20));

        lb_fn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_fn.setForeground(java.awt.Color.red);
        jPanel2.add(lb_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 80, 30));

        lb_ln.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_ln.setForeground(java.awt.Color.red);
        jPanel2.add(lb_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, 30));

        lb_pwd.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_pwd.setForeground(java.awt.Color.red);
        jPanel2.add(lb_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 90, 20));

        lb_cpwd.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_cpwd.setForeground(java.awt.Color.red);
        jPanel2.add(lb_cpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 90, 30));

        lb_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_email.setForeground(java.awt.Color.red);
        jPanel2.add(lb_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 90, 30));

        chk_agree.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        chk_agree.setForeground(java.awt.Color.red);
        jPanel2.add(chk_agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 490, 610));

        jPanel1.setBackground(new java.awt.Color(97, 212, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to CinemaWorld");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\if_Audio_-_Video_-_Game_01_2298385.png")); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 270, 240));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\if_12_1757450.png")); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 300, 250));

        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
        });
        jPanel1.add(lb_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void chkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
           String uname = txtuname.getText();
           String fname = txtfname.getText();
           String lname = txtlname.getText();
           String password = txtpwd.getText();
           String cpassword = txtcpwd.getText();
           String email = txtemail.getText();
           String checkboxx = chkb.getLabel();
           
           
               
           if(uname.isEmpty())
           {
               //throw new Exception("Blank Fields!");
               //lb_un.setText("Blank Fields");
               JOptionPane.showMessageDialog(this,"Blank field","Error",JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           if(fname.equals(""))
           {
               //lb_fn.setText("Blank feild");
               JOptionPane.showMessageDialog(this,"Blank field","Error",JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           if(lname.equals(""))
           {
               //lb_ln.setText("Blank feild");
               JOptionPane.showMessageDialog(this,"Blank field","Error",JOptionPane.ERROR_MESSAGE);
               return;
           }
          
           if(password.equals(""))
           {
               //lb_pwd.setText("Blank feild");
               JOptionPane.showMessageDialog(this,"Blank field","Error",JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           if(cpassword.equals(""))
           {
               //lb_cpwd.setText("Blank feild");
               JOptionPane.showMessageDialog(this,"Blank field","Error",JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           if(email.equals(""))
           {
               //lb_email.setText("Blank feild");
               JOptionPane.showMessageDialog(this,"Blank field","Error",JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           
           
          
               
           try{
               Class.forName("com.mysql.jdbc.Driver");
               String path = "jdbc:mysql://localhost:3306/cinema_db";
               String user= "root";
               String pass = "";
               Connection con = DriverManager.getConnection(path,user,pass);
               Statement stmt = con.createStatement();
               String query = "insert into user_tbl(username, fname, lname, pwd, email) values('"+uname+"','"+fname+"','"+lname+"','"+password+"','"+email+"')";
               
               stmt.executeUpdate(query);
               JOptionPane.showMessageDialog(null,"Registration Successful!");
               
               con.close();
           }catch(Exception ex)
           {
               JOptionPane.showMessageDialog(null,"Error found" +ex);
           }
           
           
           
           
           
           
           
           
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtunameActionPerformed

    private void txtunameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtunameMouseClicked
        // TODO add your handling code here:
        txtuname.setText("");
    }//GEN-LAST:event_txtunameMouseClicked

    private void txtfnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfnameMouseClicked
        // TODO add your handling code here:
        txtfname.setText("");
    }//GEN-LAST:event_txtfnameMouseClicked

    private void txtlnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlnameMouseClicked
        // TODO add your handling code here:
        txtlname.setText("");
    }//GEN-LAST:event_txtlnameMouseClicked

    private void txtpwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpwdFocusGained
        // TODO add your handling code here:
        txtpwd.setText("");
       
    }//GEN-LAST:event_txtpwdFocusGained

    private void txtpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpwdMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtpwdMouseClicked

    private void txtemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseClicked
        // TODO add your handling code here:
        txtemail.setText("");
    }//GEN-LAST:event_txtemailMouseClicked

    private void txtcpwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcpwdFocusGained
        // TODO add your handling code here:
        txtcpwd.setText("");
    }//GEN-LAST:event_txtcpwdFocusGained

    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseClicked
        // TODO add your handling code here:
        new Login1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_backMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chk_agree;
    private javax.swing.JCheckBox chkb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lb_back;
    private javax.swing.JLabel lb_cpwd;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_fn;
    private javax.swing.JLabel lb_ln;
    private javax.swing.JLabel lb_pwd;
    private javax.swing.JLabel lb_un;
    private javax.swing.JPasswordField txtcpwd;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
